### ISSUE TITLE
Write README.md file to describe installation and usage of BioGrakn

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/biograkn#22]
1) Downloading distribution
2) Running distribution
3) Querying it including examples

**Comment by sorsaffari** [comment]
@Irtazaraza we do have a readme for BioGrakn DN. What exactly does BioGrakn in the title of this issue refer to?

**Comment by Irtazaraza** [comment]
BioGrakn refers to everything in the repo including Disease Networks, Precision Medicine, TextMining...

It will be all combined in one ReadMe, but still will be modular.

**Comment by Irtazaraza** [comment]
fixed in PR #35
