### ISSUE TITLE
README is incomplete

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/biograkn#30]
## Description

I can't find the Precision Medicine Knowledge Graph project!

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. visit https://github.com/graknlabs/biograkn

## Expected Output

To see instructions to run:
- BioGrakn DN
- Precision Medicine
- BLAST Integration

## Actual Output

I only see instructions for running BioGrakn DN.

**Comment by Irtazaraza** [comment]
Issue #22 already exists for this.
