### ISSUE TITLE
Grakn needs Java 1.8 in order to run

### ISSUE THREAD

**Issue by davidnarganes** [graknlabs/biograkn#54]
I am getting the following error when ```./grakn server start``` inside of the unzipped https://github.com/graknlabs/biograkn#download folder:

```An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Unsupported Java version [12] found. Grakn needs Java 1.8 in order to run.
```

I currently have the newest Java version:
```openjdk 12.0.1 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

Could you please actualise the application to work with the newest Java version?

Many thanks,

David

**Comment by marco-scoppetta** [comment]
We cannot actualise the application for the time being as Cassandra does not support Java > 8.

**Comment by lolski** [comment]
Have you looked at using `jenv` which allows you to install multiple Java versions side-by-side?

**Comment by davidnarganes** [comment]
Yes, I used both Docker and ```jenv``` to get Java 8. Thanks!
