### ISSUE TITLE
Wrong content in download section?

### ISSUE THREAD

**Issue by sophie-anna** [graknlabs/biograkn#57]
Am I getting something wrong or does the unzipped file from the download section only contains "grakn-core-all-mac" instead of the BioGrakn ? Correct me if I'm wrong!

**Comment by Irtazaraza** [comment]
The distribution still contains biograkn, the name is a bug and will be fixed in the soon to be released new version.

**Comment by sophie-anna** [comment]
Thank's for the info, got BioGrakn running on Linux now. Trying to run it on Windows was the actual problem. I will close the issue.
